export default {
	"common_delivery_options" : {
		"deliver_to_door" : "Deliver to door",
		"pick_up_outside" : "Pick up outside",
		"delivery_option" : "Delivery Option",
	},
	"common_error" : {
		"email_update_success" : "更新电子邮件成功",
		"request_updated" : "Request updated",
		"updated_task_success" : "Task updated",
		"assigned_task_warning" : "任务处于'{status}'状态, 您确定您要重新分配此任务吗？",
		"gift_card_transfer_fail" : "无法转让礼品卡",
		"token_invalid" : "令牌无效, 请联系778-379-7918获取有效令牌",
		"profile_update_success" : "更新个人资料成功",
		"first_name_required" : "名字是必需的",
		"email_invalid" : "电子邮件地址的格式必须为 'someone@something.something'",
		"email_existed" : "该电子邮件已被占用.",
		"created_task_success" : "已建立任务",
		"country_required" : "请输入国家/地区代码",
		"no_courier_found" : "No Courier Found",
		"update_document_status_success" : "已更新文件状态",
		"updated_zone_success" : "已更新区域任务",
		"email_update_failed" : "更新电子邮件失败",
		"request_deleted" : "Request deleted",
		"organization_name_invalid" : "组织名称必须为5个字符或以上",
		"verification_too_many_requests" : "验证码已被请求过多次，请稍后再试",
		"phone_number_invalid" : "无效的手机号",
		"created_open_shift_success" : "已建立公开班次",
		"city_required" : "请输入城市",
		"general_error" : "发生意外错误，请稍后再试",
		"delete_customer_success" : "Cutomer deleted",
		"street_required" : "请输入街道",
		"password_invalid" : "密码无效",
		"gift_card_transfer_success" : "礼品卡转让成功",
		"updated_store_success" : "已更新商家",
		"one_more_fields_are_missing" : "一个或以上的输入框未填",
		"phone_invalid" : "Last Name is required",
		"created_store_success" : "已创建商家",
		"password_two_invalid" : "您的密码不匹配",
		"update_fee_rule_success" : "已更新付费规则",
		"delete_document_success" : "已删除文件",
		"update_open_task_status_failed" : "Failed to update open task status, please try again later",
		"unstable_network" : "网络速度较慢或不稳定，请检查您的网络连接",
		"email_required" : "请输入您的电子邮件",
		"record_not_found" : "未找到记录",
		"name_required" : "请输入店名",
		"password_one_required" : "需要密码",
		"updated_open_shift_success" : "Open shift updated",
		"phone_update_failed" : "更新电话号码失败",
		"courier_info_updated" : "已更新配送人员信息",
		"incorrect_password" : "密码错误",
		"error" : "错误",
		"password_two_required" : "需要确认密码",
		"role_not_allowed" : "Your role is not supported for this aciton",
		"login_failed" : "登录失败",
		"created_customer_success" : "Cutomer created",
		"get_verification_code_success" : "验证码已发送到您的手机",
		"organization_name_required" : "请输入组织名称",
		"deleted_open_shift_success" : "已删除公开排班",
		"updated_customer_success" : "Customer updated",
		"function_not_supported" : "此功能目前不支持，请稍后回来:)",
		"get_route_failure_message" : "由于{status}状态，方向请求失败",
		"x_is_required_create_a_store" : "需要{value}来创建商家",
		"create_fee_rule_success" : "已建立付费规则",
		"password_one_invalid" : "必须包含至少1个小写字母和1个大写字母字符，且至少包含6个字符或更长",
		"email_is_incorrect" : "用户名不存在",
		"first_name_invalid" : "名字必须至少为2个字符",
		"unable_to_load_any_data" : "无法加载数据",
		"failed_fetch_points_detail" : "无法获取积分详细信息",
		"delete_store_success" : "已删除商家",
		"logout_force_message" : "抱歉，您的帐户已从其他设备登录或超时，请重新登录。",
		"profile_update_failed" : "更新用户个人资料失败",
		"token_required" : "需要令牌",
		"password_is_incorrect" : "密码不正确",
		"delete_fee_rule_success" : "已删除付费规则",
		"failed_fetch_gift_card_detail" : "无法获取礼品卡详细信息",
		"deleted_courier_shift_success" : "已删除配送人员的排班",
		"are_you_sure_want_check_out_this_courier" : "Check out this courier",
		"region_required" : "请输入地区",
		"invalid_request" : "无效请求",
		"last_name_invalid" : "姓氏必须至少为2个字符",
		"password_required" : "请输入您的密码",
		"postal_code_required" : "请输入邮政编码",
		"unexpected_error" : "发生意外错误，请稍後再试",
		"phone_update_success" : "更新电话号码成功",
		"assigned_task_success" : "已经分配任务",
		"last_name_required" : "姓氏是必需的",
	},
	"common_modal_errors" : {
		"name_invalid" : "无效的店名",
		"display_format_required" : "请输入显示格式",
		"desired_delivery_start_required" : "请输入发货时间",
		"postal_code_invalid" : "无效的邮编",
		"phone_required" : "请输入手机号",
		"desired_pickup_start_required" : "请输入提货时间",
		"phone_invalid" : "无效的手机号",
		"postal_code_required" : "请输入邮编",
		"store_name_invalid" : "无效的店名",
		"desired_delivery_lenght_required" : "请输入发货时间长度",
		"order_id_invalid" : "无效的订单号",
		"order_id_required" : "请输入订单号",
		"desired_pickup_length_required" : "请输入提货时间长度",
		"store_name_required" : "请输入店名",
		"payment_method_invalid" : "无效的付款方式",
		"payment_method_required" : "请输入付款方法",
	},
	"common_acccount" : {
		"register_now" : "请注册",
		"register_promo_message" : "如果您正在或计划开展配送业务，需要一个系统来管理整个业务流程，您只需在此注册您的组织，这将大大简化您的业务操作流程，让您可以快速拓展。 整个系统是基于云计算计算，包括呼叫中心，派送员网站系统，配送员移动APP，商家网站系统，商家App等。",
		"create_organization" : "建立你的组织",
		"sign_up" : "注册",
		"my_assets" : "我的资产",
		"sign_up_now" : "立即注册",
		"login_here" : "这里登录",
		"logout_confirm_message" : "您确认要签退吗?",
		"address_book" : "地址簿",
		"login_with_text" : "手机短信登陆",
		"login_with_account" : "账户登陆",
		"forgot_your_pw" : "忘记密码？",
		"already_have_account" : "已经有账号？ ",
		"logout" : "登出",
		"password" : "密码",
		"password_one" : "密码",
		"log_in" : "登录",
		"become_carier" : "想成为一名快递员？",
		"password_two" : "确认密码",
		"log_in_mesage" : "登入你的账户",
		"my_account" : "我的帐户",
		"create_your_account" : "建立你的账户",
		"remember_me" : "记住我",
		"create_organaztion_mesage" : "建立组织信息",
	},
	"common_delivery_label" : {
		"school" : "School",
		"office" : "Office",
		"home" : "Home",
	},
	"common_display_format" : {
		"only_show_addresses" : "Only show adddresses",
		"hide_all_before_accept" : "Hide all before accept",
		"show_all_info" : "Show all info",
		"show_addresses_payment" : "Show addresses and payment",
	},
	"signup-page" : {
		"delivery_with_goopter_message" : "只需几个简单的步骤，您就可以获得额外收入。这是一个灵活的机会，您可以自定义以适应您的生活方式。",
		"get_paid_weekly" : "每周收入",
		"delivery_with_goopter" : "够淘递送",
		"choose_your_schedule" : "选择你的日程表",
		"choose_messages" : "您可以掌控自己的日程安排，并可以根据适合您的方式调整每周工时。 ",
		"get_paid_messages" : "在每周结束时，您的收入和小费将每周直接存入您的帐户。",
	},
	"common_language" : {
		"zh-Hant" : "繁體中文",
		"jp" : "日本語",
		"en" : "English",
		"language" : "语言",
		"zh" : "简体中文",
	},
	"common_role" : {
		"agent" : "Agent",
		"manager" : "Manager",
		"super_user" : "Super User",
		"supervisor" : "Supervisor",
	},
	"common_business_type" : {
		"jewelry" : "Jewelry",
		"appliance" : "Appliance",
		"furniture" : "Furniture",
		"restaurant" : "Restaurant",
		"grocery" : "Grocery",
		"decoration" : "Decoration",
		"fashion" : "Fashion",
	},
	"common" : {
		"cancel" : "取消",
		"enter_password" : "请输入密码",
		"about" : "关于",
		"auto_save" : "Auto Save",
		"setting" : "设置",
		"get_verification_code" : "获取验证码",
		"not_set" : "未设置",
		"customer_reviews" : "客户评论",
		"ongoing" : "Ongoing",
		"business_start_dt" : "Business Start Date",
		"action" : "行动",
		"tel" : "电话",
		"customer_name/phone" : "Customer Name/Phone",
		"dashboard" : "控制面板",
		"tasks" : "任务",
		"are_you_sure" : "你确定吗?",
		" " : " ",
		"business_name" : "Business Name",
		"margin" : "页边距",
		"add_an_option" : "Add an Option",
		"receiver" : "收货人",
		"edit" : "编辑",
		"Skipped" : "Skipped",
		"profile" : "个人资料",
		"vat" : "Value Added Tax Account Number",
		"optional" : "可选",
		"not_available" : "不可用",
		"loading" : "载入中...",
		"left" : "左",
		"nick_name" : "昵称",
		"orders" : "订单",
		"value_added_tax_account_number" : "Value Added Tax Account Number",
		"items" : "项",
		"status" : "状态",
		"out_of_stock" : "缺货",
		"role" : "Role",
		"add_an_item" : "Add an Item",
		"save" : "保存",
		"view_all" : "查看全部",
		"current" : "当前",
		"search" : "搜索",
		"delivered_items" : "Deliver Items",
		"top" : "上",
		"feerules" : "收费规则",
		"disabled" : "禁用",
		"customers" : "Customers",
		"subscribed_couriers" : "Subscribed Couriers",
		"close" : "关闭",
		"email" : "电邮",
		"staffs" : "Staffs",
		"product" : "产品",
		"contact_name" : "Contact Name",
		"no_new_noti" : "没有新提醒",
		"stores" : "商店",
		"change" : "改变",
		"last_name" : "姓",
		"email_phone" : "电子邮件/电话",
		"staff" : "Staff",
		"store" : "商店",
		"right" : "右",
		"token" : "令牌",
		"confirm" : "确认",
		"filter" : "筛选",
		"highlights" : "亮点",
		"search_customers_with" : "Search Customer With...",
		"fee_rules" : "Fee Rules",
		"relevant_reviews" : "相关评论",
		"general_settings" : "通用设置",
		"first" : "第一",
		"availabitlies" : "Availabitlies",
		"documents" : "Documents",
		"buy" : "购买",
		"second" : "第二",
		"notification" : "消息",
		"reviews" : "评论",
		"warning" : "警告",
		"newest" : "最新",
		"contact_first_name" : "Contact First Name",
		"selected" : "已选",
		"all" : "全部",
		"add" : "添加",
		"new" : "新",
		"unlock" : "解锁",
		"shared_customer" : "Share Customer",
		"customer(optional)" : "Customer(Opt)",
		"bottom" : "下",
		"business_number" : "Business Number",
		"zones" : "区域",
		"third_party_access" : "Third Party Access",
		"qty" : "数量",
		"name" : "姓名",
		"true" : "True",
		"phone_number" : "电话号码",
		"verification_code" : "验证码",
		"send" : "发送",
		"next" : "下一步",
		"no" : "否",
		"submit" : "提交",
		"back" : "后退",
		"admin" : "管理",
		"description" : "描述",
		"sort_by" : "Sort By",
		"delete" : "删除",
		"remove" : "删除",
		"general" : "通用",
		"allow_third_party_access" : "Allow Third Party Access",
		"reload" : "刷新",
		"expired" : "已过期",
		"ratings" : "评级",
		"ready" : "准备",
		"contact_last_name" : "Contact Last Name",
		"ok" : "确认",
		"first_name" : "名",
		"couriers" : "配送人员",
		"get_started" : "开始",
		"quantity" : "数量",
		"previous" : "上一步",
		"apply" : "应用",
		"yes" : "是",
		"false" : "False",
		"business_building_name" : "Business Building Name",
		"share_address_book" : "Share Address Book",
		"clear_all" : "清除所有",
		"label" : "Label",
		"clear_fliter" : "清除篩選條件",
		"home" : "首页",
		"gift_cards" : "礼品卡",
		"search_stores_with" : "Search Store With...",
		"special_instruction" : "Special Instruction",
		"comment" : "备注",
		"category" : "类别",
		"assign" : "分配",
		"customer" : "客户",
	},
	"common_shifts" : {
		"out_of_stock" : "售罄",
		"open_shifts" : "Open Shifts",
		"bonus_pay" : "提成",
		"openShifts" : "公开排班",
		"shift_length" : "工时",
		"max_couriers" : "配送人员上限",
		"end_time" : "结束时间",
		"active" : "进行中",
		"courier_shifts_filter" : "配送人员的排班过滤器",
		"shift_info" : "班次讯息",
		"zone_id" : "区域",
		"start_time" : "起始时间",
		"shift_type" : "班次类型",
		"overflow" : "临时轮班",
		"inactive" : "停止",
		"zone" : "区域",
		"shifts" : "Shifts",
		"courier_shifts" : "Courier Shifts",
		"cancelled" : "已取消",
		"closed" : "已关闭",
		"courierShifts" : "配送人员的排班",
		"oncall" : "随传随到",
		"regular" : "常规",
		"status" : "状态",
	},
	"common_†ime" : {
		"date" : "日期",
		"thu" : "THU",
		"select_date" : "选择日期",
		"saturday" : "Saturday",
		"tue" : "TUE",
		"delivery_time" : "配送时间",
		"mon" : "MON",
		"sun" : "SUN",
		"yesterday" : "昨天",
		"closed_all_day" : "全天歇业",
		"today" : "今天",
		"wed" : "WED",
		"wednesday" : "Wednesday",
		"friday" : "Friday",
		"add_periods" : "Add Periods",
		"fri" : "FRI",
		"created_utc" : "Created Time",
		"monday" : "Monday",
		"last_month" : "上個月",
		"open_all_day" : "全天营业",
		"select_time" : "选择时间",
		"expiry_date" : "过期日",
		"sat" : "SAT",
		"thursday" : "Thursday",
		"this_week" : "本星期",
		"open_247" : "Open 24/7",
		"updated_utc" : "Updated Time",
		"sunday" : "Sunday",
		"this_month" : "這個月",
		"tuesday" : "Tuesday",
		"last_updated_at" : "Last Updated at",
		"pickup_time" : "取货时间",
		"expiration_utc" : "Expiry Date",
		"last_week" : "上个星期",
	},
	"common_relationship_to_store" : {
		"owner" : "Owner",
		"marketer" : "Marketer",
		"accountant" : "Accountant",
		"onsite_manager" : "Onsite Manager",
		"restaurant_staff" : "Restaurant Staff",
		"general_manager" : "Genral Manager",
		"chef" : "Chef",
		"relationship_to_store" : "Relationship to Store",
	},
	"landing-page" : {
		"download_apps_message" : "下载适用于iPhone或Android智能手机的最新版配送应用程序。您必须在手机上才能下载该应用程序",
		"welcome_to_courier_portal" : "欢迎来到快递门户网站",
	},
	"common_address" : {
		"country" : "国家",
		"address" : "地址",
		"buzzer" : "门铃",
		"city" : "城市",
		"map_search" : "地图搜索",
		"billing_address" : "账单地址",
		"add_address" : "添加地址",
		"quick_map_search" : "快速地图搜索",
		"unit" : "单元",
		"province" : "省份",
		"street" : "街道",
		"shipping_address" : "配送地址",
		"postal_code" : "邮编",
	},
	"common_task" : {
		"ready_to_drive_to_store" : "准备开往商店",
		"courier_accept_the_task" : "配送人员已接受了任务",
		"parked_at_the_store" : "已停靠在商店",
		"not_assigned" : "没有被分配",
		"ready_drive_to_customer" : "准备开往顾客",
		"collected_item" : "已经收取货物",
		"rejected_by_courier" : "已被配送人员拒绝",
		"assigned" : "已被分配",
		"parked_at_customer" : "已停靠在顾客",
		"delivered_orded" : "已发货",
	},
	"common_courier_status" : {
		"applying" : "Applying",
		"approved" : "Approved",
		"rejected" : "Rejected",
		"pending" : "Pending",
		"inreview" : "Inreview",
	},
	"common_price" : {
		"points_payment" : "积分支付",
		"shipping_and_handling" : "配送费",
		"discount" : "折扣",
		"amt" : "总额",
		"billing_shipping" : "结算和运输",
		"tips" : "小费",
		"delivery_fee" : "配送费",
		"total" : "Total",
		"balance" : "余额",
		"total_paid" : "已付款",
		"price" : "价格",
		"store_discount" : "商家折扣",
		"customer_info" : "客户信息",
		"other_payment_info" : "其他付款信息",
		"total_before_tax" : "税前金额",
		"payment_info" : "付款信息",
		"shopping" : "购物",
		"total_due" : "应付款",
		"min_amount" : "最低金额",
		"tax" : "税",
		"item(s)" : "物件",
		"gift_card_payment" : "礼品卡支付",
		"done" : "完成",
		"subtotal" : "商品總價",
		"delivery_info" : "运输信息",
		"max_amount" : "最高金额",
		"order_total" : "总价",
		"coupon_discount" : "打折券",
	},
	"common_item_option" : {
	},
	"common_documents" : {
		"vehicle_insurance" : "Vehicle Insurance",
		"vehicle_registration" : "Vehicle Registration",
		"profile_photo" : "Profile Photo",
		"incorporation_certificate" : "Incorporation Certificate",
		"proof_of_work_eligibility" : "Proof of Work Eligibility",
		"store_owner_id" : "Store Owner Id",
		"business_license" : "Business License",
		"driver_license" : "Driver License",
		"void_check" : "Void Check",
		"store_image" : "Store Image",
	},
	"common_restaurant_type" : {
		"Russian" : "俄罗斯菜式",
		"Chinese: Cantonese" : "中式: 粤菜",
		"Asian Fusion" : "亚洲美食",
		"Burgers" : "汉堡",
		"Seafood" : "海鲜",
		"Alcohol" : "酒精",
		"Bubble Tea" : "泡沫奶茶",
		"Chinese: Hot Pot" : "中式: 火锅",
		"Kosher" : "符合犹太教规的菜式",
		"BBQ" : "烧烤",
		"Vegetarian / Vegan" : "素食/全素食者",
		"restaurant_type" : "Restaurant Type",
		"Spanish" : "西班牙菜式",
		"Southern" : "美国南部风味",
		"Thai" : "泰式",
		"Malaysian" : "马来西亚菜",
		"Juice & Smoothies" : "果汁和冰沙",
		"African: Ethiopian" : "非洲风味: 埃塞俄比亚菜式",
		"African: Other" : "非洲风味: 其他",
		"Japanese: Other" : "日式: 其他",
		"Bakery" : "烘培",
		"Latin American: Other" : "南美风: 其他",
		"Dessert: Other" : "点心: 其他",
		"Chinese: Taiwanese" : "中式: 台式",
		"Japanese: Ramen" : "日式: 拉面",
		"Burmese" : "缅甸风味",
		"Breakfast &amp;Brunch" : "早餐&amp;早午餐",
		"Fish and Chips" : "鱼和薯片",
		"Bar / Pub Food" : "酒吧/酒馆食物",
		"Chicken" : "鸡肉",
		"Salad / Sandwiches" : "沙拉/三明治",
		"Asian: Other" : "亚洲风味: 其他",
		"Comfort Food" : "舒心美食",
		"Italian" : "意式",
		"American" : "北美风味",
		"Modern Australian" : "现代澳大利亚风",
		"German" : "德式",
		"European: Other" : "欧式: 其他",
		"Soul Food" : "美国非裔传统菜",
		"French" : "法式",
		"Wings" : "鸡翅",
		"Middle Eastern" : "中东风味",
		"Indonesian" : "印尼餐",
		"Chinese: Other" : "中式: 其他",
		"Snacks" : "零嘴",
		"Georgian" : "喬治亞菜式",
		"Steakhouse" : "牛排店",
		"Coffee & Tea" : "咖啡和茶",
		"Chinese: Noodles & Dumplings" : "Chinese: Noodles & Dumplings",
		"Mexican" : "墨西哥风",
		"Japanese: Sushi" : "日式: 寿司",
		"Chinese: Sichuan" : "中式: 川菜",
		"Korean" : "韩式",
		"Ice Cream & Frozen Yogurt" : "冰淇淋和冰冻酸奶",
		"Pizza" : "披萨",
		"Mediterranean" : "地中海风",
		"Cajun / Creole" : "卡津/克里奥尔菜式",
		"Indian" : "印度",
		"Vietnamese" : "越式",
		"Halal" : "清真",
		"Caribbean" : "加勒比风",
		"Other" : "其他",
	},
	"common_column_titles" : {
		"pickup_range" : "取货时间",
		"per_km_fee_to_customer_desc" : "支付给配送员的超过平价配送距离后的每公里费用",
		"allow_third_party_access_tooltip" : "Allow Third Party (API Key) access and edit store information",
		"time_limit" : "时间限制",
		"last_seen" : "最近在线",
		"base_distance_desc" : "公司付给配送员的平价配送距离",
		"hours/week" : "小时/周",
		"office_info" : "办公室信息",
		"active_zones" : "活跃区域",
		"active_zones_desc" : "配送员当前的工作区域",
		"pending_stores" : "等待提交中的商家",
		"per_km_fee_to_store_desc" : "从配送员到商家的每公里的费用",
		"store_was_not_entered_or_not_recognized" : "Please enter location from info",
		"contact" : "联系人",
		"working_state" : "工作状态",
		"action" : "操作",
		"subscribed_zones" : "订阅的区域",
		"from" : "发货人",
		"info" : "信息",
		"number_of_locations" : "分店数量",
		"pendingStores" : "等待提交中的商家",
		"delivery_range" : "送达时间",
		"generate_next_order_id" : "Generate next order Id",
		"collection_fee_per_min_desc" : "超过免费等待时间的每分钟等候费用(给配送员)",
		"phone" : "手机号码",
		"active_stores" : "已批准的商家",
		"please_enter_destination_info" : "Please enter destination info",
		"name" : "姓名",
		"dollar_min" : "$/分钟",
		"base_fee_desc" : "支付给配送员的平价配送费用",
		"order_id" : "订单号",
		"can_override" : "允许用户修改配送费",
		"status" : "配送状态",
		"fee_rule" : "付费规则",
		"pending_store" : "等待提交中的商家",
		"can_override_desc" : "是否允许商家修改配送费用",
		"zone_name" : "区域名称",
		"contact_info" : "联系方式",
		"confirmed" : "已确认",
		"collection_time_limit_desc" : "到商家提货时候的免费等待时间",
		"calulate_estimated_delivery_Fee" : "Calculate Esistmated Delivery Fee",
		"subscribed_zones_desc" : "配送员选择的工作区域。",
		"business_type" : "生意类型",
		"store_name" : "商店名称",
		"website" : "网站",
		"address" : "地址",
		"dollar/km_store" : "$/km (商店)",
		"base_distance" : "平价配送距离",
		"dollar/km_customer" : "$/km (顾客)",
		"store" : "店家",
		"working_state_desc" : "快递员在工作场所的出勤状况。",
		"base_fee" : "起步价",
		"names" : "名称",
		"share_address_book_tooltip" : "Allow Organization to access store customer address book",
		"delivery_fee_descript" : "Delivery Fee is calcated based on store fee rule if it is not set",
		"report" : "报表",
		"to" : "收货人",
		"pending_store(other)" : "等待提交中的商家（其他）",
		"fee_rule_was_not_assigned_to_the_selected_store_or_fee_rule_not_recognized" : "Fee rule is not assigned to the selected store or fee rule is not recognized",
	},
	"common_payment_method" : {
		"paid" : "Paid",
		"pay_later_with_card" : "Pay later with card",
		"cash" : "Cash",
	},
	"common_setting" : {
		"driver_check_in_tooltip" : "Only assigning task to a courier that is check in",
		"auto_assign_driver_distance" : "Driver Distance",
		"show_phone" : "Show Phone",
		"show_name" : "Show Name",
		"show_to_name_tooltip" : "Display location to (customer) name on courier task report",
		"show_to_mask_phone_tooltip" : "Display location to (customer) phone on courier on-going task",
		"driver_has_shift_tooltip" : "Only assigning task to a courier that has a shift",
		"time_slot_gap_tooltip" : "Gap between each availabilities time slot (in mins)",
		"show_from_address_tooltip" : "Display location from (store)  address on courier task report",
		"show_to_address_tooltip" : "Display location to  (customer) address on courier task report",
		"require_availability_tooltip" : "Require Couriers to submit availabities",
		"mask_phone" : "Mask Phone",
		"time_range_tooltip" : "Availabilities time slot time range length (in mins)",
		"call_forward_valid_period" : "Call Forward Valid Period",
		"others" : "Others",
		"time_slot" : "Availabilities Time Slot",
		"show_from_mask_phone_tooltip" : "Display location from (store)  phone on courier on-going task",
		"assign_statuses_tooltip" : "Only assigning task when task is updated to below status",
		"auto_assign" : "Auto Assign",
		"has_no_tasks" : "Has no task",
		"show_from_name_tooltip" : "Display location from (store) name on courier task report",
		"auto_assign_tooltip" : "Auto assign task to a courier",
		"show_from_phone_tooltip" : "Display location from (store)  phone on courier task report",
		"has_no_tasks_tooltip" : "Only assigning task to a courier that has no task",
		"show_from_special_instruction_tooltip" : "Display location from (store)  special instruction on courier task report",
		"driver_has_shift" : "Driver has Shift",
		"driver_distance" : "Driver Distance",
		"call_forward_valid_period_tooltip" : "Call Forward Valid Period",
		"show_address" : "Show Address",
		"show_to_special_instruction_tooltip" : "Display location to (customer) special instructio on courier task report",
		"show_to_phone_tooltip" : "Display location to  (customer) phone on courier task report",
		"task_display" : "Task Display",
		"driver_check_in" : "Driver Check in",
		"driver_distance_tooltip" : "Only assigning task to a courier that is within x km",
		"time_slot_gap" : "Time Slot Gap",
		"allowed_app" : "Allowed Apps",
		"show_special_insturction" : "Show Special Instruction ",
		"third_party" : "Third Party",
		"allowed_app_tooltip" : "Apps allowed to modifty and access stores' information using third part (API) keys",
		"assign_statuses" : "Auto Assign Statuses",
		"require_availability" : "Require Availability",
	},
	"common_modals" : {
		"organization_info" : "组织信息",
		"bonus" : "奖金",
		"created_range" : "任务创建时间范围",
		"show_addresses_payment_acount_but_no_items" : "显示地址及配送费，但不显示产品信息",
		"expected_pickup_utc" : "预计取货时间",
		"amount_to_collect" : "收取金额",
		"max_location_age" : "位置的最早时间",
		"re-assign" : "重新分配",
		"expected_time_info" : "期待时间信息",
		"couriers_filter" : "筛选配送员",
		"search_couriers_with" : "搜索配送员",
		"expected_delivery_utc" : "预计配送时间",
		"user_info" : "用户信息",
		"fee_rule_info" : "收费规则",
		"desired_pickup_range" : "要求取货时间",
		"desired_delivered" : "期待送达",
		"payment_method" : "支付方式",
		"store_info" : "商店信息",
		"address_info" : "地址信息",
		"expected_pickup_time" : "预计取货时间",
		"transit_pay_from_driver_to_store" : "配送费 (按司机到商家之间的距离来算)",
		"desired_delivery_start" : "要求配送时间",
		"check_in" : "Check in",
		"switch_organization" : "更换组织",
		"organization_name" : "组织名称",
		"status_time_line" : "时间状态线",
		"task_details" : "任务详情",
		"has_shift" : "Has Shift",
		"task" : "任务",
		"add_task" : "添加任务",
		"amount_to_pay" : "支付商家金额",
		"courier" : "配送人员",
		"courier_report" : "配送员报表",
		"shows_addresses_but_no_item_payment_amount_before_accept" : "在接受之前显示地址但不显示产品信息及配送费",
		"task_filter" : "任务筛选",
		"region" : "地区",
		"option" : "选项",
		"has_location" : "Has Location",
		"fit_shift" : "Fit Shift",
		"desired_delivery_lenght" : "要求配送时间跨度",
		"stated_payment_method" : "预计付款方式",
		"distance" : "距离",
		"assigned_range" : "任务分配时间范围",
		"time_info" : "配送时间",
		"user_profile" : "用户资料",
		"transit_pay_from_store_to_customer" : "配送费 (按商家到客戶间的距离来算)",
		"collection_fee_per_min" : "超过免费等待时间后的每分钟额外费用",
		"delivered_range" : "配送距离",
		"duration" : "时长",
		"expected_delivery_time" : "预计配送时间",
		"courier_name" : "配送员名",
		"assign_task" : "分配任务",
		"desired_delivery_range" : "要求配送时间",
		"time_range" : "时间范围",
		"per_km_fee_to_store" : "司机到商家每公里交通补贴",
		"hide_detail_before_accept" : "接受前隐藏配送细节",
		"desired_pickup_start" : "要求取货时间",
		"deadline" : "截止日期",
		"stated_tips" : "声明小费金额",
		"delivery" : "配送",
		"other_info" : "Other Info",
		"items_info" : "商品信息",
		"collection_time_limit_required" : "请输入提货时间限制",
		"collection_time_limit" : "免费的等待时间限制",
		"time_zone" : "时区",
		"store(optional)" : "商家 (可选的)",
		"desired_pickup_length" : "要求取货时间跨度",
		"show_all_info" : "显示所有信息",
		"default_fee_rule" : "Default fee rule",
		"order_info" : "配送信息",
		"search_tasks_with" : "搜索任务",
		"zones_filter" : "区域筛选",
		"per_km_fee_to_customer" : "超过平价配送费用后每公里的额外费用",
		"open_task" : "Open task",
		"pick_up" : "取货",
		"organization" : "组织",
		"display_format" : "显示格式",
		"working_info" : "工作状态信息",
		"no_shift_info" : "No Shift Info",
		"organ_store" : "组织及商家",
		"driver_compensate_for_waiting" : "配送员在商家等待的补偿费用",
	},
	"common_country" : {
		"united_states" : "美国",
		"canada" : "加拿大",
		"china" : "中国",
		"south_korea" : "韩国",
	},
	"common_working_state" : {
		"checked_in" : "Checked In",
		"working_states" : "Working States",
		"on_break" : "On break",
		"checked_out" : "Checked out",
	}
}